# Generated by Django 3.1 on 2021-07-22 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA content",
            reverse_sql="DROP SCHEMA content",
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'возрастной ценз',
                'verbose_name_plural': 'возрастные цензы',
                'db_table': 'content"."certificates',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'db_table': 'content"."genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание')),
                ('imdb_identifier', models.CharField(blank=True,
                 max_length=255, verbose_name='IMDB идентификатор')),
                ('creation_date', models.DateField(blank=True,
                 null=True, verbose_name='дата создания фильма')),
                ('file_path', models.FileField(blank=True,
                 upload_to='movies/', verbose_name='файл')),
                ('rating', models.FloatField(blank=True, default=0, validators=[
                 django.core.validators.MinValueValidator(0)], verbose_name='рейтинг')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='movies', to='movies.certificate', verbose_name='возрастной ценз')),
            ],
            options={
                'verbose_name': 'кинопроизведение',
                'verbose_name_plural': 'кинопроизведения',
                'db_table': 'content"."movies',
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип кинопроизведения',
                'verbose_name_plural': 'типы кинопроизведений',
                'db_table': 'content"."movie_types',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True,
                 null=True, verbose_name='дата рождения')),
                ('gender', models.TextField(choices=[
                 ('male', 'мужской'), ('female', 'женский')], null=True, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'персона',
                'verbose_name_plural': 'персоны',
                'db_table': 'content"."persons',
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'content"."person_roles',
            },
        ),
        migrations.CreateModel(
            name='MoviePersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='дата создания')),
                ('movie', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
                ('person_role', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='movies.personrole')),
            ],
            options={
                'verbose_name': 'персона фильма',
                'verbose_name_plural': 'персоны фильмов',
                'db_table': 'content"."movie_person_role',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='дата создания')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='gms', related_query_name='gm', to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='mgs', related_query_name='mg', to='movies.movie')),
            ],
            options={
                'verbose_name': 'жанр фильма',
                'verbose_name_plural': 'жанры фильма',
                'db_table': 'content"."movie_genre',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(
                blank=True, through='movies.MovieGenre', to='movies.Genre', verbose_name='жанр фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(
                blank=True, through='movies.MoviePersonRole', to='movies.Person', verbose_name='персона фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='movies', to='movies.movietype', verbose_name='тип кинопроизведения'),
        ),
    ]
