# Generated by Django 3.1 on 2021-07-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('name',), name='certificates_name_uidx'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name',), name='genres_name_uidx'),
        ),
        migrations.AddConstraint(
            model_name='moviepersonrole',
            constraint=models.UniqueConstraint(fields=('movie_id', 'person_id', 'person_role_id'), name='movie_person_role_main_uidx'),
        ),
        migrations.AddConstraint(
            model_name='movietype',
            constraint=models.UniqueConstraint(fields=('name',), name='movie_types_name_uidx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('full_name',), name='persons_full_name_uidx'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.UniqueConstraint(fields=('name',), name='person_roles_name_uidx'),
        ),
    ]
