# Generated by Django 3.1 on 2021-07-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210722_1444'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='persons_full_name_uidx',
        ),
    ]
