# Generated by Django 3.1 on 2021-07-29 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210722_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'age qualification',
                     'verbose_name_plural': 'age qualifications'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'ganre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'film work',
                     'verbose_name_plural': 'film works'},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'verbose_name': 'film genre',
                     'verbose_name_plural': 'film genres'},
        ),
        migrations.AlterModelOptions(
            name='moviepersonrole',
            options={'verbose_name': 'film person',
                     'verbose_name_plural': 'film persons'},
        ),
        migrations.AlterModelOptions(
            name='movietype',
            options={'verbose_name': 'type of film',
                     'verbose_name_plural': 'types of film'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person',
                     'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='personrole',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(
                blank=True, through='movies.MovieGenre', to='movies.Movie', verbose_name='genre film'),
        ),
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(
                blank=True, through='movies.MoviePersonRole', to='movies.Movie', verbose_name='person film'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='movies', to='movies.certificate', verbose_name='age qualification'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='creation_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='movie creation date '),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file_path',
            field=models.FileField(
                blank=True, upload_to='movies/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(
                through='movies.MovieGenre', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_identifier',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='IMDB identifier'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(
                blank=True, through='movies.MoviePersonRole', to='movies.Person', verbose_name='film person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, default=0, validators=[
                                    django.core.validators.MinValueValidator(0)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='movies', to='movies.movietype', verbose_name='type of film'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='moviepersonrole',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='movietype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='date of birth '),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(choices=[(
                'male', 'male gender '), ('female', 'female gender ')], null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
