# Generated by Django 3.1 on 2021-08-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210729_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AddField(
            model_name='movie',
            name='person_roles',
            field=models.ManyToManyField(through='movies.MoviePersonRole', to='movies.PersonRole'),
        ),
    ]
