version: '3.9'
services:

  db:
    image: postgres:13
    container_name: yandex_p_db
    env_file:
      - movies_admin/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - yandex_p_network

  app:
    build:
      context: ./movies_admin
      dockerfile: Dockerfile.prod
    container_name: yandex_p_app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./movies_admin/.env
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - "8000"
    networks:
      - yandex_p_network
    depends_on:
      - db

  nginx:
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile.prod
    container_name: yandex_p_nginx
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - yandex_p_network

volumes:
  postgres-data:
  static_volume:

networks:
  yandex_p_network: